services:
  rabbitmq:
    image: "rabbitmq:3.13.7-management"
    container_name: "rabbitmq"
    restart: always
    ports:
      - "5672:5672"  # AMQP protocol port
      - "15672:15672"  # Management UI (should be secured in production)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - backend-dev

  api-gateway-service:
    build:
      context: ./api-gateway-service
      target: development
    ports:
      - "3000:3000"
    env_file:
      - ./api-gateway-service/.env
    environment:
      AUTH_ADDRESS: http://authentication-service:3001
      ENT_TENDER_ADDRESS: http://ent-tenders-service:3002
      ENT_OFFERS_ADDRESS: http://ent-offers-service:3003
    command: npm run dev
    networks:
      - backend-dev

  authentication-service:
    build:
      context: ./authentication-service
      target: development
    ports:
      - "3001:3001"
    env_file:
      - ./authentication-service/.env
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    command: npm run dev
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - backend-dev

  ent-tenders-service:
    build:
      context: ./ent-tenders-service
      target: development
    ports:
      - "3002:3002"
    env_file:
      - ./ent-tenders-service/.env
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    command: npm run dev
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - backend-dev

  ent-offers-service:
    build:
      context: ./ent-offers-service
      target: development
    ports:
      - "3003:3003"
    env_file:
      - ./ent-offers-service/.env
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    command: npm run dev
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - backend-dev

networks:
  backend-dev:
    driver: bridge
