services:
  api-gateway-service:
    build:
      context: ./api-gateway-service
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./api-gateway-service:/api-gateway-service
    env_file:
      - ./api-gateway-service/.env
    environment:
      AUTH_ADDRESS: http://authentication-service:3001
      ENT_TENDER_ADDRESS: http://ent-tenders-service:3002
      ENT_OFFERS_ADDRESS: http://ent-offers-service:3003
    command: npm run dev

  authentication-service:
    build:
      context: ./authentication-service
      target: development
    ports:
      - "3001:3001"
    volumes:
      - ./authentication-service:/authentication-service
    env_file:
      - ./authentication-service/.env
    command: npm run dev

  ent-tenders-service:
    build:
      context: ./ent-tenders-service
      target: development
    ports:
      - "3002:3002"
    volumes:
      - ./ent-tenders-service:/ent-tenders-service
    env_file:
      - ./ent-tenders-service/.env
    command: npm run dev

  ent-offers-service:
    build:
      context: ./ent-offers-service
      target: development
    ports:
      - "3003:3003"
    volumes:
      - ./ent-offers-service:/ent-offers-service
    env_file:
      - ./ent-offers-service/.env
    command: npm run dev
